### PR TITLE
Remove dangling volumes

### PR DESCRIPTION
**Pull request by ymilki**
Sometimes volumes are left behind from docker-compose. `docker volume ls -f dangling=true` lists them all. These volumes aren't removed by dcgc because they aren't associated with any containers or images. They are left in /var/lib/docker/volumes indefinitely until removed.

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM

**Comment by ymilki** [comment]
The only filter for volume deletion is dangling=True. docker volume inspect only provides the keys Name, Driver, Mountpoint, Label.

I suspect we may want either an exclude list or another filter on Labels (labels=null perhaps) because volumes can be attached to containers.

**Comment by Bert-R** [comment]
I tried running Custodian with the new ``--dangling-volumes`` flag, like this:

```
docker run -i --rm -v /var/run/docker.sock:/var/run/docker.sock yelp/docker-custodian dcgc --dangling-volumes --max-container-age ...
```

But that causes the following error:
```
Getting all containers
Found 11 containers
Getting all containers
Found 11 containers
Getting all images
Found 33 images
Getting dangling volumes
Traceback (most recent call last):
  File "/usr/bin/dcgc", line 9, in <module>
    load_entry_point('docker-custodian==0.7.0', 'console_scripts', 'dcgc')()
  File "/code/docker_custodian/docker_gc.py", line 222, in main
    cleanup_volumes(client, args.dry_run)
  File "/code/docker_custodian/docker_gc.py", line 163, in cleanup_volumes
    dangling_volumes = get_dangling_volumes(client)
  File "/code/docker_custodian/docker_gc.py", line 80, in get_dangling_volumes
    log.info("Found %s dangling volumes", len(volumes))
TypeError: object of type 'NoneType' has no len()
```

Is it me? Or should I log an issue?

**Comment by dnephin** [comment]
It sounds like it found no dangling volumes. Please open an issue about it.

**Comment by Bert-R** [comment]
Done. See #41

**Pull request merged**
