### PR TITLE
Remove py26 support, code cleanup

### PR DESCRIPTION
**Pull request by kentwills**
Removed legacy support for py2.6 and cleaned up some of the code.  @solarkennedy can you review this?

@bukzor, @analogue  FYI

### CODE REVIEW

**Comment by solarkennedy** [comment]
lgtm!

**Comment by bukzor** [comment]
shipit

**Comment by kentwills** [comment]
@dnephin, want to merge this in for me?

**Comment by solarkennedy** [comment]
I can.

**Comment by kentwills** [comment]
@solarkennedy thanks!

**Pull request merged**
